version: '2'
services:
  app:
    build:
     context: .
    image: zinuzoid/bff-optimizer
    ports:
      - 3000:3000
    environment:
      - PORT=3000 
      - NODE_ENV=production
    command: npm start
      
